import './globals.css'
import type { Metadata } from 'next'
import { Gruppo } from 'next/font/google'

const gruppo = Gruppo({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={gruppo.className}>{children}</body>
    </html>
  )
}
